### PR TITLE
Basic css applied

### PR DESCRIPTION
**Pull request by Steventyler5**

### CODE REVIEW

**Comment by ahmedansari153** [comment]
Doing stuff without us tsk tsk. :+1:

**Comment by mbennette85** [comment]
:+1:

**Comment by Steventyler5** [comment]
egg egg egg egg egg egg egg egg egg egg egg egg egg egg egg

**Comment by ahmedansari153** [comment]
What do you mean egg?

**Comment by ahmedansari153** [comment]
Tyler your fired.

**Pull request merged**
